### ISSUE TITLE
Adding the Scalable Angular Spectrum Method

### ISSUE THREAD

**Issue by roflmaostc** [chromatix-team/chromatix#106]
Hi!

I was wondering if a PR would be appreciated to include the [Scalable Angular Spectrum Method](https://github.com/bionanoimaging/Scalable-Angular-Spectrum-Method-SAS/blob/main/SAS_pytorch.ipynb)?

It's very similar to a single step Fresnel method, having magnification properties but without paraxial approximation. It's just 3 FFTs and some phase factors. And zero padding, extraction. Do you have methods for the latter ones already?

Thanks :)

Felix

**Comment by GJBoth** [comment]
Hi Felix, that PR would be very much appreciated! There's some functions for padding and cropping fields [here](https://github.com/chromatix-team/chromatix/blob/7a97163ff9f0dc819eae1dc6f30ac300f2c51fa8/src/chromatix/field.py#L399) - is that sufficient for what you need?

**Comment by roflmaostc** [comment]
That's great.

Is there anything else which I have to consider? Is it fine if I dump the existing code and adapt it to jax?

**Comment by GJBoth** [comment]
Closed by #121
