### ISSUE TITLE
"trainable" location in 101 docs chromatix

### ISSUE THREAD

**Issue by researcherofreality** [chromatix-team/chromatix#131]
In the docs https://chromatix.readthedocs.io/en/latest/101/ first code-block, I have an issue with importing "trainable" from chromatix.utils; it seems to be in chromatix.elements instead. 

-Vojko

**Comment by GJBoth** [comment]
Thanks! We'll fix it.

@hosseybposh You checked the tutorials right? Did we miss something?

**Comment by diptodip** [comment]
I think this time we got them all (also thanks to issue #108). Fixes and a new release coming soon!

**Comment by GJBoth** [comment]
Fixed by #136.
