### ISSUE TITLE
OpticalSystem arbitrary plane field

### ISSUE THREAD

**Issue by apsk14** [chromatix-team/chromatix#19]
It would be nice to query an OpticalSystem at an arbitrary plane and get the field there.

**Comment by GJBoth** [comment]
This is technically already possible, but we should probably make some examples and filters to make this easier: https://flax.readthedocs.io/en/latest/guides/extracting_intermediates.html#use-capture-intermediates

**Comment by srinituraga** [comment]
I think this is a really cool idea, and I don’t think it’s solved by simply capturing intermediates. Currently, we do propagation with special propagators for 2f lenses, etc. Such propagators only let us capture the field at those particular special planes a focal distance away from the lens.

But what if you wanted to capture the field at a plane that’s not at one of those locations? Right now, that requires that we construct a new optical system which potentially included a Fresnel propagation to the desired plane.

Can we separate the definition of an optical system, which should really just be a description of the hardware components of the system, from queries about the light field at any arbitrary plane along the propagation axis?
