### ISSUE TITLE
Make public slack or discord?

### ISSUE THREAD

**Issue by GJBoth** [chromatix-team/chromatix#54]

**Comment by mkitti** [comment]
Also consider https://zulip.com/for/open-source/ or https://gitter.im/ (now Matrix based)

**Comment by mkitti** [comment]
Zulip examples:
1. https://napari.zulipchat.com/
2. https://imagesc.zulipchat.com/
3. https://rust-lang.zulipchat.com/
4. http://julialang.zulipchat.com/
